modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="esoterica"
version="${file.jarVersion}"
displayName="Esoterica"
logoFile="esoterica.png"
credits="Credits go here"
authors="Authors go here"
description=''' '''
[[dependencies.esoterica]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.esoterica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"
