modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="fufo"
version="${file.jarVersion}"
displayName="Fundamental Forces"
logoFile="fundamental_forces.png"
credits="Credits go here"
authors="Authors go here"
description=''' '''
[[dependencies.fufo]]
    modId="pollen"
    mandatory=true
    versionRange="[FORGE-1.18.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.fufo]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fufo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
